apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx-deployment"
  namespace: "nginx-operator-ns"
  labels:
    k8s-app: "nginx"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: "nginx"
  template:
    metadata:
      labels:
        k8s-app: "nginx"
    spec:
      containers:
        - name: "nginx"
          image: "nginx:latest"
          command:
            - "nginx"
