apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx-deployment"
  namespace: "nginx-operator-system"
  labels:
    k8s-app: "nginx"
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: "nginx"
  template:
    metadata:
      labels:
        k8s-app: "nginx"
    spec:
      containers:
        - name: "nginx"
          image: "nginx:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          command: ["nginx", "-g", "daemon off;"]
