# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-system/some-secret
  name: nginxoperators.operator.cloudops.com
spec:
  group: operator
  names: []
  scope: Namespaced
  versions: []